framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: 'redis://redis:6379'
        
        pools:
            # Cache for SkinBaron price data
            cache.skinbaron_prices:
                adapter: cache.adapter.redis
                default_lifetime: 3600  # 1 hour
                
            # Cache for calculated statistics
            cache.skinbaron_stats:
                adapter: cache.adapter.redis
                default_lifetime: 1800  # 30 minutes
                
            # Cache for API responses
            cache.skinbaron_api:
                adapter: cache.adapter.redis
                default_lifetime: 300   # 5 minutes