framework:
    messenger:
        failure_transport: failed

        transports:
            # Use Doctrine for message queue (stores in PostgreSQL)
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: true
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 4000
            
            # Failed messages also in database
            failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route messages here later